"""
Report Generation module for creating markdown and PDF reports.
"""
from pathlib import Path
from datetime import datetime
from typing import List
import markdown
from models import Source, AnalysisResult, ResearchReport
from config import OUTPUT_DIR
from logger_setup import log


class ReportGenerator:
    """Generates research reports in Markdown and PDF formats."""
    
    def __init__(self):
        Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)
        log.info("ReportGenerator initialized")
    
    def generate_markdown(self, report: ResearchReport) -> str:
        """Generate a complete markdown report."""
        log.info(f"Generating markdown report for: {report.topic}")
        
        md = []
        
        # Title and metadata
        md.append(f"# {report.title}\n")
        md.append(f"**Topic:** {report.topic}\n")
        md.append(f"**Generated:** {report.created_at.strftime('%Y-%m-%d %H:%M')}\n")
        # Authors (gathered from sources if available)
        authors = []
        for s in report.sources:
            if getattr(s, 'author', None):
                authors.append(s.author)
        authors = [a for a in dict.fromkeys(authors) if a]
        if authors:
            md.append(f"**Authors:** {', '.join(authors)}\n")
        md.append("---\n")
        
        # Table of Contents
        md.append("## Table of Contents\n")
        toc_items = []
        idx = 1
        for section_name in report.sections.keys():
            anchor = section_name.lower().replace(' ', '-')
            toc_items.append(f"{idx}. [{section_name}](#{anchor})")
            idx += 1
        toc_items.append(f"{idx}. [Sources](#sources)")
        md.extend(toc_items)
        md.append("")
        md.append("---\n")
        
        # Contributors
        if getattr(report, 'contributors', None):
            md.append("## Contributors\n")
            for c in report.contributors:
                md.append(f"- {c}")
            md.append("")

        # Sections
        for section_name, content in report.sections.items():
            # Replace generic [Author] placeholder with first available author
            if '[Author]' in content:
                replacement = authors[0] if authors else 'Unknown'
                content = content.replace('[Author]', replacement)
            md.append(f"## {section_name}\n")
            # Attribution
            author = report.section_authors.get(section_name) if getattr(report, 'section_authors', None) else None
            if author:
                md.append(f"*Written by: {author}*\n")
            md.append(f"{content}\n")
        
        # Analysis Results
        if report.analysis:
            md.append("## Statistical Analysis\n")
            md.append(f"- **Total Words Analyzed:** {report.analysis.word_count:,}")
            md.append(f"- **Sentences:** {report.analysis.sentence_count:,}")
            md.append(f"- **Avg. Sentence Length:** {report.analysis.avg_sentence_length} words")
            md.append(f"- **Overall Sentiment:** {report.analysis.sentiment_label.title()} ({report.analysis.sentiment_score})\n")
            
            md.append("### Top Keywords\n")
            for word, count in list(report.analysis.top_keywords.items())[:10]:
                md.append(f"- {word}: {count}")
            md.append("")
            
            # Chart references
            if report.analysis.chart_paths:
                md.append("### Visualizations\n")
                for path in report.analysis.chart_paths:
                    chart_name = Path(path).stem.replace("_", " ").title()
                    md.append(f"![{chart_name}]({path})\n")
        
        # Sources (detailed table)
        md.append("## Sources\n")
        if report.sources:
            md.append('| # | Title | Authors | Publisher / Journal | Published | DOI | URL | Raw Path |')
            md.append('|---|-------|---------|---------------------|----------:|-----|-----|----------|')
            for i, source in enumerate(report.sources, 1):
                title = source.title or ''
                authors = getattr(source, 'author', '') or ''
                publisher = getattr(source, 'publisher', '') or ''
                pubdate = getattr(source, 'publish_date', '') or ''
                doi = getattr(source, 'doi', '') or ''
                url = source.url or ''
                rawp = getattr(source, 'raw_path', '') or ''
                md.append(f"| {i} | {title} | {authors} | {publisher} | {pubdate} | {doi} | {url} | {rawp} |")
        else:
            md.append('No sources were collected.')
        md.append("")
        
        # Footer
        md.append("---")
        md.append("*Generated by Multi-Agent Research Assistant*")
        
        report.markdown_content = "\n".join(md)
        log.debug(f"Generated {len(report.markdown_content)} chars of markdown")
        
        return report.markdown_content
    
    def save_markdown(self, report: ResearchReport) -> str:
        """Save the markdown report to a file."""
        filename = f"{OUTPUT_DIR}/report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(report.markdown_content)
        
        log.info(f"Saved markdown report: {filename}")
        return filename
    
    def generate_html(self, report: ResearchReport) -> str:
        """Convert markdown to styled HTML."""
        html_template = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{title}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, sans-serif;
            max-width: 900px;
            margin: 0 auto;
            padding: 40px;
            line-height: 1.6;
            color: #333;
        }}
        h1 {{ color: #2C3E50; border-bottom: 3px solid #3498DB; padding-bottom: 10px; }}
        h2 {{ color: #34495E; margin-top: 30px; }}
        h3 {{ color: #7F8C8D; }}
        a {{ color: #3498DB; }}
        img {{ max-width: 100%; height: auto; margin: 20px 0; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        ul {{ padding-left: 20px; }}
        li {{ margin: 5px 0; }}
        hr {{ border: none; border-top: 1px solid #eee; margin: 30px 0; }}
        code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }}
        .metadata {{ color: #7F8C8D; font-size: 0.9em; }}
    </style>
</head>
<body>
{content}
</body>
</html>
"""
        html_content = markdown.markdown(
            report.markdown_content,
            extensions=['tables', 'fenced_code', 'toc']
        )
        
        full_html = html_template.format(
            title=report.title,
            content=html_content
        )
        
        return full_html
    
    def save_html(self, report: ResearchReport) -> str:
        """Save as HTML file."""
        filename = f"{OUTPUT_DIR}/report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        
        html = self.generate_html(report)
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(html)
        
        log.info(f"Saved HTML report: {filename}")
        return filename
